# Generated by Django 5.1.2 on 2024-10-27 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, max_length=100)),
                ('symbol', models.TextField(max_length=50)),
                ('data_path', models.TextField(default=None, max_length=500)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('requested_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StocksCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerMinuteTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_path', models.TextField(max_length=500)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('requested_count', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.stockinformation')),
            ],
        ),
        migrations.CreateModel(
            name='DayTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_path', models.TextField(max_length=500)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('requested_count', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.stockinformation')),
            ],
        ),
        migrations.AddField(
            model_name='stockinformation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.stockscategory'),
        ),
    ]
